#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2026 O.S. Systems Software LTDA.

# Run tests for boards. This script must be run from the root directory of the code repository.

basedir=$(dirname $(dirname $(readlink -f $0)))

cd $basedir

if [ -z $(find -'(' -name sample.yaml -o -name testcase.yaml -')' -a -print -quit) ]; then
    echo "INFO: No test cases found"
    exit 0
fi

west twister -G --testsuite-root . --tag motor_control $@
